### ISSUE TITLE
Update flight schedules

### ISSUE THREAD

**Issue by nikojohnarellano** [wackydnbc/wackywebapp#27]
Some flights are way overestimated. We should make the flights realistic per the Assignment instructions

**Comment by brynbeaudry** [comment]
each airport in your "network" is visited at least twice a day. 
each of three planes making a two return trips to one your "network" destinations

no departures before 08:00
no landings after 22:00
minimum 30 minutes between a plane's landing and any subsequent departure
all of your fleet must be back at your airline base by the end of the day

flight times need to be reasonable, based on distance between airports, airplane cruising speed, and a 10 minute buffer added to each flight in order to reach cruising/landing speed and altitude
